import { useState, useRef } from 'react';
import { useApp } from '@/context/AppContext';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { 
  AlertTriangle, 
  Camera, 
  MapPin, 
  Phone, 
  Bell,
  CheckCircle,
  Clock,
  X,
  Send
} from 'lucide-react';
import { format } from 'date-fns';
import { toast } from 'sonner';

const EmergencySection = () => {
  const { currentUser, emergencyAlerts, addEmergencyAlert, updateEmergencyAlert } = useApp();
  const [showCreateForm, setShowCreateForm] = useState(false);
  const [message, setMessage] = useState('');
  const [location, setLocation] = useState('');
  const [capturedPhoto, setCapturedPhoto] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const isAsha = currentUser?.role === 'asha';

  const handlePhotoCapture = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setCapturedPhoto(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleSubmitAlert = async () => {
    if (!message.trim()) {
      toast.error('Please describe your emergency');
      return;
    }

    // We need a profile ID to link alerts - for now use a placeholder
    await addEmergencyAlert({
      user_id: currentUser?.id || '',
      user_name: currentUser?.name || '',
      user_role: currentUser?.role || 'pregnant',
      type: 'urgent',
      message: message.trim(),
      location: location || currentUser?.village || null,
      photo_url: capturedPhoto || null,
      assigned_asha_id: currentUser?.assignedAshaId || null,
    });

    setShowCreateForm(false);
    setMessage('');
    setLocation('');
    setCapturedPhoto(null);
  };

  const updateAlertStatus = async (alertId: string, status: 'acknowledged' | 'resolved') => {
    await updateEmergencyAlert(alertId, { status });
    toast.success(`Alert ${status === 'acknowledged' ? 'acknowledged' : 'resolved'}`);
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'active':
        return <span className="px-3 py-1 rounded-full text-xs font-medium bg-destructive text-destructive-foreground flex items-center gap-1"><Bell className="w-3 h-3" /> Active</span>;
      case 'acknowledged':
        return <span className="px-3 py-1 rounded-full text-xs font-medium bg-warning text-warning-foreground flex items-center gap-1"><Clock className="w-3 h-3" /> Acknowledged</span>;
      case 'resolved':
        return <span className="px-3 py-1 rounded-full text-xs font-medium bg-success text-success-foreground flex items-center gap-1"><CheckCircle className="w-3 h-3" /> Resolved</span>;
      default:
        return null;
    }
  };

  const generateReport = (alert: typeof emergencyAlerts[0]) => {
    const report = `
EMERGENCY ALERT REPORT
======================
Date: ${format(new Date(alert.created_at), 'PPpp')}
Patient: ${alert.user_name}
Type: ${alert.type.toUpperCase()}
Status: ${alert.status.toUpperCase()}

DETAILS:
${alert.message}

Location: ${alert.location || 'Not specified'}
Alert ID: ${alert.id}

---
Generated by Maternova Healthcare System
    `.trim();

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `emergency-report-${alert.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report downloaded');
  };

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-heading font-bold text-foreground">Emergency Alerts</h1>
          <p className="text-muted-foreground">Real-time emergency notification system</p>
        </div>
        {!isAsha && (
          <Button 
            onClick={() => setShowCreateForm(true)}
            className="btn-emergency"
          >
            <AlertTriangle className="w-5 h-5 mr-2" />
            Send Emergency Alert
          </Button>
        )}
      </div>

      {/* Create Alert Form */}
      {showCreateForm && (
        <Card className="p-6 border-destructive/50 bg-destructive/5">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold text-destructive">🚨 Create Emergency Alert</h2>
            <Button variant="ghost" size="icon" onClick={() => setShowCreateForm(false)}>
              <X className="w-5 h-5" />
            </Button>
          </div>
          
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium mb-2">Describe Your Emergency *</label>
              <Textarea
                placeholder="Please describe what's happening..."
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                rows={3}
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-2">
                <MapPin className="w-4 h-4 inline mr-1" />
                Location
              </label>
              <Input
                placeholder="Your current location"
                value={location}
                onChange={(e) => setLocation(e.target.value)}
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-2">
                <Camera className="w-4 h-4 inline mr-1" />
                Capture Photo (Optional)
              </label>
              <input
                type="file"
                accept="image/*"
                capture="environment"
                ref={fileInputRef}
                onChange={handlePhotoCapture}
                className="hidden"
              />
              <Button
                variant="outline"
                onClick={() => fileInputRef.current?.click()}
                className="w-full"
              >
                <Camera className="w-4 h-4 mr-2" />
                {capturedPhoto ? 'Photo Captured ✓' : 'Take Photo'}
              </Button>
              {capturedPhoto && (
                <div className="mt-2 relative">
                  <img src={capturedPhoto} alt="Captured" className="w-full max-h-48 object-cover rounded-lg" />
                  <Button
                    variant="destructive"
                    size="icon"
                    className="absolute top-2 right-2"
                    onClick={() => setCapturedPhoto(null)}
                  >
                    <X className="w-4 h-4" />
                  </Button>
                </div>
              )}
            </div>

            <Button onClick={handleSubmitAlert} className="w-full bg-destructive hover:bg-destructive/90">
              <Send className="w-4 h-4 mr-2" />
              Send Alert to ASHA & Hospital
            </Button>
          </div>
        </Card>
      )}

      {/* Alerts List */}
      <div className="space-y-4">
        {emergencyAlerts.length === 0 ? (
          <Card className="p-8 text-center">
            <CheckCircle className="w-12 h-12 mx-auto text-success mb-4" />
            <h3 className="text-lg font-semibold">No Emergency Alerts</h3>
            <p className="text-muted-foreground">All is well! No active emergencies.</p>
          </Card>
        ) : (
          emergencyAlerts.map(alert => (
            <Card 
              key={alert.id} 
              className={`p-6 ${
                alert.status === 'active' 
                  ? 'border-destructive/50 bg-destructive/5' 
                  : ''
              }`}
            >
              <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-2">
                    {getStatusBadge(alert.status)}
                    <span className="text-sm text-muted-foreground">
                      {format(new Date(alert.created_at), 'PPp')}
                    </span>
                  </div>
                  
                  <h3 className="text-lg font-semibold text-foreground mb-1">
                    {alert.user_name}
                  </h3>
                  <p className="text-foreground mb-3">{alert.message}</p>
                  
                  {alert.location && (
                    <p className="text-sm text-muted-foreground flex items-center gap-1">
                      <MapPin className="w-4 h-4" /> {alert.location}
                    </p>
                  )}

                  {alert.photo_url && (
                    <div className="mt-3">
                      <img 
                        src={alert.photo_url} 
                        alt="Emergency photo" 
                        className="max-w-xs rounded-lg border"
                      />
                    </div>
                  )}
                </div>

                {isAsha && (
                  <div className="flex flex-col gap-2">
                    {alert.status === 'active' && (
                      <Button 
                        variant="outline"
                        onClick={() => updateAlertStatus(alert.id, 'acknowledged')}
                      >
                        <CheckCircle className="w-4 h-4 mr-2" />
                        Acknowledge
                      </Button>
                    )}
                    {alert.status !== 'resolved' && (
                      <Button 
                        variant="default"
                        className="bg-success hover:bg-success/90"
                        onClick={() => updateAlertStatus(alert.id, 'resolved')}
                      >
                        <CheckCircle className="w-4 h-4 mr-2" />
                        Mark Resolved
                      </Button>
                    )}
                    <Button 
                      variant="ghost"
                      onClick={() => generateReport(alert)}
                    >
                      📄 Download Report
                    </Button>
                    <Button variant="ghost">
                      <Phone className="w-4 h-4 mr-2" />
                      Call Patient
                    </Button>
                  </div>
                )}
              </div>
            </Card>
          ))
        )}
      </div>
    </div>
  );
};

export default EmergencySection;
